name: Feature Request
description: Suggest an idea for Wiki-Bot
labels: ['enhancement']
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description / Motivation
      description: A clear and concise description of what you want to achieve or what problem you're solving.
      placeholder: What should this feature do and why is it useful?
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
